version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: expense_tracker_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: Azhagammai@25879865
    volumes:
      - mongodb_data:/data/db
      - ./mongodb_init:/docker-entrypoint-initdb.d
    networks:
      - expense_tracker_network

  # Expense Tracker API
  api:
    build: .
    container_name: expense_tracker_api
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://admin:Azhagammai%4025879865@mongodb:27017/expense_tracker?authSource=admin
      - JWT_SECRET_KEY=KdQ8MBny_gA-Rt7pdVTP69wnzxvJxnelYqBx8VaXQBY
      - FLASK_ENV=production
    depends_on:
      - mongodb
    networks:
      - expense_tracker_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    container_name: expense_tracker_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    networks:
      - expense_tracker_network

volumes:
  mongodb_data:
    driver: local

networks:
  expense_tracker_network:
    driver: bridge