version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: expense_tracker_mongodb_local
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: Azhagammai@25879865
    volumes:
      - mongodb_data:/data/db
    networks:
      - expense_tracker_network

  # Expense Tracker API
  api:
    build: 
      context: .
      dockerfile: Dockerfile.local
    container_name: expense_tracker_api_local
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://admin:Azhagammai%4025879865@mongodb:27017/expense_tracker?authSource=admin
      - JWT_SECRET_KEY=KdQ8MBny_gA-Rt7pdVTP69wnzxvJxnelYqBx8VaXQBY
      - FLASK_ENV=development
    depends_on:
      - mongodb
    networks:
      - expense_tracker_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mongodb_data:
    driver: local

networks:
  expense_tracker_network:
    driver: bridge
